### ISSUE TITLE
 docker exec kafka bash - java.net.UnknownHostException: myHost: unknown error

### ISSUE THREAD

**Issue by anasanjaria** [apache/incubator-openwhisk#2469]
## Environment details:

* distributed deployment but using LAN (2 system, 1 with openwhisk framework, and trying to build and distribute OpenWhisk docker images on another system with IP 192.189.0.102)
* ubuntu 16.04 LTS

## Issue:
I have followed the deployment guide [here](https://github.com/apache/incubator-openwhisk/blob/master/ansible/README_DISTRIBUTED.md). The following command produces an error:

`ansible-playbook -i environments/<environment> openwhisk.yml`

```
 docker exec kafka bash -c 'unset JMX_PORT; kafka-topics.sh --create --topic health --replication-factor 1 --partitions 1 --zookeeper anjaria:2181 --config retention.bytes=1073741824 --config retention.ms=3600000 --config segment.bytes=536870912'
Exception in thread "main" org.I0Itec.zkclient.exception.ZkException: Unable to connect to anjaria:2181
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:72)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1228)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:106)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:88)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:56)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: java.net.UnknownHostException: anjaria: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:70)
	... 7 more
```
# Possible solution
The possible solution is to add entry in the /etc/hosts file. But I think this entry should be inside kafka container and not inside the system with IP 192.189.0.102. I checked hosts file of kafka container and I don't find any such entry. 

`docker exec kafka bash -c 'cat /etc/hosts'`

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.6	zookeeper 73776ae8172f
172.17.0.7	1cfd770b93d3
```

I tried to add an entry inside host file using command 

`docker exec kafka bash -c 'echo 192.189.0.102 anjaria > sudo /etc/hosts'`

I am not sure why I need to do this step as [here](https://github.com/apache/incubator-openwhisk/blob/master/ansible/roles/kafka/tasks/deploy.yml#L39), the environment variable is already set.

**Comment by anasanjaria** [comment]
I have used IP address instead inside the ansible inventory file. Sorry, it was not a bug.
