### ISSUE TITLE
only 4 concurrent containers running on each worker

### ISSUE THREAD

**Issue by pxgao** [apache/incubator-openwhisk#2515]
Hi there,
          I am having a 5-worker node openwhisk cluster. When i submit actions, there are only 20 actions running, although i successfully submitted 150 actions. 
          I check the worker machines and each machine only has 4 actions running. My machine has 32 cores and > 200G memory. So I want to increase the degree of parallelism each machine. Please help!

**Comment by markusthoemmes** [comment]
Hi, you want to adjust CPUCore and CPUShare parameters:

```
numcore: 2
coreshare: 2
```

`numcore` should be the number of CPU cores on the machine, `coreshare` the number of containers you want to spawn per core. Effectively you'll get core * share containers in parallel.

**Comment by pxgao** [comment]
So I should put this two lines in this file?
openwhisk/ansible/environments/distributed/group_vars/all

**Comment by markusthoemmes** [comment]
Unfortunately, it's not per env. configurable as of today. You'll need to change in the global group_vars/all.

Feel free to open a PR making this configurable. It would be along these lines:

```
numcore: "{{ invoker_numcore | default(2) }}"
...
```

**Comment by pxgao** [comment]
Thanks. I don't really care if its per environment reconfigurable.
So I just need to change ansible/group_vars/all this file and recompile?

**Comment by pxgao** [comment]
I changed the numcore in ansible/group_vars/all from 2 to 32. But I can't submit action now. I get
error: Unable to invoke action 'long-lambda': Post https://10.0.5.11/api/v1/namespaces/_/actions/long-lambda?blocking=false&result=false: dial tcp 10.0.5.11:443: getsockopt: connection refused

**Comment by pxgao** [comment]
I was able to increase numcore to 4 without any problem. But if i further increase it. I get the following error when i submit action.
error: Unable to invoke action 'long-lambda': Post https://10.0.5.11/api/v1/namespaces/_/actions/long-lambda?blocking=false&result=false: dial tcp 10.0.5.11:443: getsockopt: connection refused

**Comment by markusthoemmes** [comment]
Doesn't strike me as obvious why that could be related 🤔 . Have you looked into controller logs?

**Comment by pxgao** [comment]
Here is my controller.log, seems that the invoker health test failed....

[2017-07-21T04:41:28.263Z] [INFO] Slf4jLogger started
[2017-07-21T04:41:28.574Z] [INFO] [??] [Config] environment set value for consulserver.host
[2017-07-21T04:41:28.576Z] [INFO] [??] [Config] environment set value for whisk.version.date
[2017-07-21T04:41:28.577Z] [INFO] [??] [Config] environment set value for whisk.version.buildno
[2017-07-21T04:41:28.577Z] [INFO] [??] [Config] environment set value for consul.host.port4
[2017-07-21T04:41:28.578Z] [INFO] [??] [Config] environment set value for port
[2017-07-21T04:41:28.578Z] [INFO] [??] [WhiskConfig] reading properties from consul at 10.0.5.160:8500
[2017-07-21T04:41:29.694Z] [INFO] [#sid_130] [Controller] starting controller instance 0 [marker:controller_startup0_count:1130]
[2017-07-21T04:41:29.717Z] [INFO] [??] [LoadBalancerService] blackboxFraction = 0.1
[2017-07-21T04:41:29.718Z] [INFO] [??] [LoadBalancerService] activationCountBeforeNextInvoker = 10
[2017-07-21T04:41:29.890Z] [INFO] [#sid_120] [WhiskAction] [GET] serving from datastore: id: whisk.system/invokerHealthTestAction [marker:database_cacheMiss_count:1328]
[2017-07-21T04:41:29.891Z] [INFO] [#sid_120] [CouchDbRestStore] [GET] 'ubuntu_ip-10-0-5-147_whisks' finding document: 'id: whisk.system/invokerHealthTestAction' [marker:database_getDocument_start:1329]
[2017-07-21T04:41:29.951Z] [INFO] [#sid_120] [CouchDbRestStore] [GET] 'ubuntu_ip-10-0-5-147_whisks' failed to get document: 'id: whisk.system/invokerHealthTestAction'; http status: '401 Unauthorized' [marker:database_getDocument_finish:1390:61]
[2017-07-21T04:41:29.952Z] [INFO] [#sid_120] [WhiskAction] invalidating id: whisk.system/invokerHealthTestAction
[2017-07-21T04:41:29.955Z] [ERROR] [#sid_120] [CouchDbRestStore] [GET] 'ubuntu_ip-10-0-5-147_whisks' internal error, doc: 'id: whisk.system/invokerHealthTestAction', failure: 'Unexpected http response code: 401 Unauthorized' [marker:database_getDocument_error:1392:63]
[2017-07-21T04:41:29.956Z] [ERROR] [#sid_120] [LoadBalancerService] error creating test action for invoker health: java.lang.Exception: Unexpected http response code: 401 Unauthorized
[2017-07-21T04:41:29.958Z] [ERROR] Unexpected http response code: 401 Unauthorized
akka.actor.ActorInitializationException: akka://controller-actor-system/user/controller-service: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Exception: Unexpected http response code: 401 Unauthorized
	at whisk.core.database.CouchDbRestStore$$anonfun$10.apply(CouchDbRestStore.scala:167)
	at whisk.core.database.CouchDbRestStore$$anonfun$10.apply(CouchDbRestStore.scala:142)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	... 4 more
[2017-07-21T04:41:30.051Z] [ERROR] Monitored actor [Actor[akka://controller-actor-system/user/controller-service#-1128887570]] terminated
akka.actor.DeathPactException: Monitored actor [Actor[akka://controller-actor-system/user/controller-service#-1128887570]] terminated
[2017-07-21T04:41:30.056Z] [INFO] Message [akka.io.Tcp$Bound] from Actor[akka://controller-actor-system/system/IO-TCP/selectors/$a/2#-1261594500] to Actor[akka://controller-actor-system/user/IO-HTTP/listener-0#1047161669] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by pxgao** [comment]
And this line 
https://github.com/apache/incubator-openwhisk/blob/master/core/invoker/src/main/scala/whisk/core/container/ContainerPool.scala#L821
sets the numcore to 4. 

Is that a default value or its hardcoded numcore maximum?

**Comment by markusthoemmes** [comment]
@pxgao in your database credentials seem to be wrong.

**Comment by pxgao** [comment]
Where can i find the database credential?

**Comment by pxgao** [comment]
Thank you. I resolved the issue. Simply change the num core to 32 would work. The "connection refused" error is unrealted
