### ISSUE TITLE
Travis raises permission error

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk#2712]
Collecting setuptools

  Downloading setuptools-36.4.0-py2.py3-none-any.whl (478kB)

    100% |████████████████████████████████| 481kB 1.6MB/s 

Collecting six

  Using cached six-1.10.0-py2.py3-none-any.whl

Installing collected packages: setuptools, six

  Found existing installation: setuptools 36.3.0

    Uninstalling setuptools-36.3.0:

Exception:

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main

    status = self.run(options, args)

  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run

    prefix=options.prefix_path,

  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 778, in install

    requirement.uninstall(auto_confirm=True)

  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall

    paths_to_remove.remove(auto_confirm)

  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove

    renames(path, new_path)

  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames

    shutil.move(old, new)

  File "/usr/lib/python2.7/shutil.py", line 303, in move

    os.unlink(src)

OSError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning

The command "pip install --upgrade pip setuptools six" failed and exited with 2 during .

**Comment by csantanapr** [comment]
How do we proceed?
I think is related to Travis recent updates
https://blog.travis-ci.com/2017-08-29-trusty-image-updates
