### ISSUE TITLE
required_python_version not in python_version, NoneType

### ISSUE THREAD

**Issue by Palt0n** [apache/incubator-openwhisk#2749]
## Environment details:

Windows 10, Python 3.6.2, Pipenv 7.0.1

## Steps to reproduce the issue:
1. pip install pipenv
2. I tried pipenv --three (doesn't work because its windows so it's ok)  
3. Then did pipenv --python C:\Users\Erwin\AppData\Local\Programs\Python\Python36-32\ (which gives the error msg)

## Provide the expected results and outputs:

```
pipenv successful?
```

## Provide the actual results and outputs:
```

C:\Users\Erwin>pipenv --python C:\Users\Erwin\AppData\Local\Programs\Python\Python36-32\python.exe
Creating a virtualenv for this project…
Using C:\Users\Erwin\AppData\Local\Programs\Python\Python36-32\python.exe to create virtualenv…
Running virtualenv with interpreter C:\Users\Erwin\AppData\Local\Programs\Python\Python36-32\python.exe
Using base prefix 'C:\\Users\\Erwin\\AppData\\Local\\Programs\\Python\\Python36-32'
New python executable in C:\Users\Erwin\.virtualenvs\Erwin-Se-U2teM\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\Erwin\.virtualenvs\Erwin-Se-U2teM
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Erwin\AppData\Local\Programs\Python\Python36-32\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 1159, in cli
    ensure_project(three=three, python=python)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 395, in ensure_project
    ensure_pipfile(validate=validate)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli.py", line 261, in ensure_pipfile
    project.create_pipfile(python=python)
  File "c:\users\erwin\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\project.py", line 288, in create_pipfile
    data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
```

## Additional information you deem important:
Have python 2.7 also installed, but 'python' in the cli refers to python 3

**Comment by Palt0n** [comment]
Sorry, found out it was a Pipfile issue.
