### ISSUE TITLE
Question with ZOOKEEPER_HOST

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk#2967]
In the source code of [ansible/roles/invoker/tasks/deploy.yml](https://github.com/apache/incubator-openwhisk/blob/master/ansible/roles/invoker/tasks/deploy.yml#L122), it says:
```
-e ZOOKEEPER_HOST='{{ groups['kafka']|first }}'
```

zookeeper host is set to kafka host? Is it a mistake or is it intentional?

@dgrove-oss

**Comment by markusthoemmes** [comment]
That is intentional in that in the current deployment there is only one kafka and one zookeeper which are assumed to reside on the same machine. This will like change with #2744.

**Comment by daisy-ycguo** [comment]
I deployed with a distributed Kafka and Zookeeper. I set ZOOKEEPER_HOST to zookeeper host and I set ZOOKEEPER_HOST_PORT to zookeeper port. But I got below error:
```
[2017-11-14T09:09:52.637Z] [INFO] Opening socket connection to server zookeeper.openwhisk.svc.cluster.local/10.0.0.114:3888. Will not attempt to authenticate using SASL (unknown error)
[2017-11-14T09:09:52.637Z] [WARN] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
 at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
 at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
```
Am I missing any configures?

**Comment by dgrove-oss** [comment]
One thought:  be sure you are deploying zookeeper 3.4 (not 3.5).  The version of curator-recipes we are using to talk to zookeeper only works with 3.4.  We need a different version to talk to zookeeper 3.5.

**Comment by daisy-ycguo** [comment]
This one is resolved. The problem is that we set wrong port of zookeeper. 
Mark it as resolved and close it.
