### ISSUE TITLE
DockerContainerTests heseinbug

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3008]
Failed in this Travis CI build 307526229

```
whisk.core.containerpool.docker.test.DockerContainerTests > DockerContainer should eventually terminate even if no sentinels can be found FAILED
    org.scalatest.exceptions.TestFailedException: 246 was greater than or equal to 100, but 246 was not less than 200
        at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
        at whisk.core.containerpool.docker.test.DockerContainerTests$$anonfun$22.apply(DockerContainerTests.scala:582)
        at whisk.core.containerpool.docker.test.DockerContainerTests$$anonfun$22.apply(DockerContainerTests.scala:560)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
        at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
        at whisk.core.containerpool.docker.test.DockerContainerTests.org$scalamock$scalatest$AbstractMockFactory$$super$withFixture(DockerContainerTests.scala:59)
        at org.scalamock.scalatest.AbstractMockFactory$$anonfun$withFixture$1.apply(AbstractMockFactory.scala:35)
        at org.scalamock.scalatest.AbstractMockFactory$$anonfun$withFixture$1.apply(AbstractMockFactory.scala:34)
        at org.scalamock.MockFactoryBase$class.withExpectations(MockFactoryBase.scala:51)
        at whisk.core.containerpool.docker.test.DockerContainerTests.withExpectations(DockerContainerTests.scala:59)
        at org.scalamock.scalatest.AbstractMockFactory$class.withFixture(AbstractMockFactory.scala:34)
        at whisk.core.containerpool.docker.test.DockerContainerTests.withFixture(DockerContainerTests.scala:59)
        at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
        at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
        at whisk.core.containerpool.docker.test.DockerContainerTests.org$scalatest$BeforeAndAfterEach$$super$runTest(DockerContainerTests.scala:59)
        at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
        at whisk.core.containerpool.docker.test.DockerContainerTests.runTest(DockerContainerTests.scala:59)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
        at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
        at org.scalatest.Suite$class.run(Suite.scala:1147)
        at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
        at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
        at whisk.core.containerpool.docker.test.DockerContainerTests.org$scalatest$BeforeAndAfterAll$$super$run(DockerContainerTests.scala:59)
        at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
        at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
        at whisk.core.containerpool.docker.test.DockerContainerTests.run(DockerContainerTests.scala:59)
```

**Comment by rabbah** [comment]
@cbickel @markusthoemmes  do you have a suggestion other than doing this?

```bash
diff --git a/tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala b/tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
index 1519d09..f6ed7f1 100644
--- a/tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
+++ b/tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
@@ -579,7 +579,7 @@ class DockerContainerTests
 
     val (interval, processedLog) = durationOf(awaitLogs(container.logs(limit = 1.MB, waitForSentinel = true)))
 
-    interval.toMillis should (be >= waitForLogs.toMillis and be < (waitForLogs * 2).toMillis)
+    interval.toMillis should (be >= waitForLogs.toMillis and be < (waitForLogs * 3).toMillis)
 ```
