### ISSUE TITLE
services.KafkaConnectorTests.Kafka heisenbug

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3022]
This issue is to collect the intermittent issues. We found three different types so far:
- [ ] `This server is not the leader for that topic-partition.`
- [ ] `services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after shutdown one of instances FAILED
    org.scalatest.exceptions.TestFailedException: 0 was not equal to 1`
- [ ] hanging while trying to retrieve a message https://github.com/apache/incubator-openwhisk/issues/3022#issuecomment-348948838

Observed one failure in jenkins:

```bash
services.KafkaConnectorTests.Kafka connector should send and receive a kafka message even after shutdown one of instances

Error Message

org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.

Stacktrace

org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.

Standard Output

[2017-11-28T15:07:19.923Z] [INFO] Slf4jLogger started
Received 1. Took 407 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 3 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 2. Took 11 msec: List(Tue Nov 28 15:07:20 EST 2017, Tue Nov 28 15:07:31 EST 2017)

Received 3. Took 9 msec: List(Tue Nov 28 15:07:20 EST 2017, Tue Nov 28 15:07:31 EST 2017, Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 7 msec: List(Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 10 msec: List(Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 22 msec: List(Tue Nov 28 15:07:52 EST 2017)


```

**Comment by jeremiaswerner** [comment]
@devbv I caught a stacktrace of a slightly different error but related
```
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after shutdown one of instances FAILED
    org.scalatest.exceptions.TestFailedException: 0 was not equal to 1
        at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
        at services.KafkaConnectorTests$$anonfun$6$$anonfun$apply$2.apply$mcVI$sp(KafkaConnectorTests.scala:142)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at services.KafkaConnectorTests$$anonfun$6.apply(KafkaConnectorTests.scala:134)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
        at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
        at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
        at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
        at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
        at org.scalatest.Suite$class.run(Suite.scala:1147)
        at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
        at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
        at services.KafkaConnectorTests.org$scalatest$BeforeAndAfterAll$$super$run(KafkaConnectorTests.scala:43)
        at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
        at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
        at services.KafkaConnectorTests.run(KafkaConnectorTests.scala:43)
```

**Comment by devbv** [comment]
@jeremiaswerner Can we reduce number of kafka instance to 1, until we can handle all kafka related problem?

**Comment by markusthoemmes** [comment]
Had an instance of this where the test is hanging on receiving more messages.

```
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after shutdown one of instances STANDARD_OUT
    Send message to topic.

    Successfully sent message to topic: Dinosaurs-0@0

    Receiving message from topic.

    Received 1. Took 76 msec: List(Mon Dec 04 06:37:04 EST 2017)

    Send message to topic.

    Successfully sent message to topic: Dinosaurs-0@1

    Receiving message from topic.

    Received 1. Took 13 msec: List(Mon Dec 04 06:37:04 EST 2017)

    Send message to topic.

    Successfully sent message to topic: Dinosaurs-0@2

    Receiving message from topic.
```

**Comment by jeremiaswerner** [comment]
@devbv thanks for looking into it. I think for now we can leave it enabled to catch those intermittent issues. Once it gets annoying we can should go back to 1 kafka node. I think we have found three different issues so far. I've put them as checkboxes to the description.

**Comment by devbv** [comment]
@jeremiaswerner 
Today, I could recreate those and more intermittent issues in my environments. I've almost resolved them but need little more time to make it clear and add new PR.  And we also need a time for code review, so how about going back to 1 kafka node just for one week? The PR already got approved. #3048

**Comment by jeremiaswerner** [comment]
@devbv cool 👍   thank you!

**Comment by chetanmeh** [comment]
Got 2 failures

1. send and receive a kafka message even after session timeout

```
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after session timeout STANDARD_OUT
    Send message to topic.
    Successfully sent message to topic: Dinosaurs-0@1
    Receiving message from topic.
    Received 1. Took 22 msec: List(Wed Jan 10 06:26:31 UTC 2018)
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after session timeout FAILED
    org.scalatest.exceptions.TestFailedException: "Wed Jan 10 06:2[6:31] UTC 2018" was not equal to "Wed Jan 10 06:2[8:39] UTC 2018"
        at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
        at services.KafkaConnectorTests$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(KafkaConnectorTests.scala:120)
        at services.KafkaConnectorTests$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(KafkaConnectorTests.scala:106)
        at scala.collection.immutable.Range.foreach(Range.scala:160)
        at services.KafkaConnectorTests$$anonfun$2.apply$mcV$sp(KafkaConnectorTests.scala:106)
        at services.KafkaConnectorTests$$anonfun$2.apply(KafkaConnectorTests.scala:106)
        at services.KafkaConnectorTests$$anonfun$2.apply(KafkaConnectorTests.scala:106)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
        at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
        at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
        at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
        at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
        at org.scalatest.Suite$class.run(Suite.scala:1147)
        at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
        at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
        at services.KafkaConnectorTests.org$scalatest$BeforeAndAfterAll$$super$run(KafkaConnectorTests.scala:43)
        at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
        at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
        at services.KafkaConnectorTests.run(KafkaConnectorTests.scala:43)
```
2. send and receive a kafka message which sets up the topic
```
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message which sets up the topic STANDARD_OUT
    Send message to topic.
    Successfully sent message to topic: Dinosaurs-0@0
    Receiving message from topic.
    Received 0. Took 127898 msec: List()
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message which sets up the topic FAILED
    org.scalatest.exceptions.TestFailedException: 0 was not greater than or equal to 1
        at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
        at services.KafkaConnectorTests$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(KafkaConnectorTests.scala:99)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at services.KafkaConnectorTests$$anonfun$1.apply$mcV$sp(KafkaConnectorTests.scala:96)
        at services.KafkaConnectorTests$$anonfun$1.apply(KafkaConnectorTests.scala:96)
        at services.KafkaConnectorTests$$anonfun$1.apply(KafkaConnectorTests.scala:96)
        at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
        at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
        at org.scalatest.Transformer.apply(Transformer.scala:22)
        at org.scalatest.Transformer.apply(Transformer.scala:20)
        at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
        at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
        at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
        at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
        at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
        at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
        at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
        at org.scalatest.Suite$class.run(Suite.scala:1147)
        at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
        at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
        at services.KafkaConnectorTests.org$scalatest$BeforeAndAfterAll$$super$run(KafkaConnectorTests.scala:43)
        at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
        at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
        at services.KafkaConnectorTests.run(KafkaConnectorTests.scala:43)
```
