### ISSUE TITLE
ActivationsApiTests fails with no results from list query

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3027]
Observed in couple of Travis PR builds.

```
whisk.core.controller.test.ActivationsApiTests > Activations API should get summary activation by namespace and action name FAILED
    org.scalatest.exceptions.TestFailedException: 2 was not equal to 0
        at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
        at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
        at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
        at whisk.core.controller.test.ActivationsApiTests$$anonfun$11$$anonfun$apply$30$$anonfun$apply$31.apply(ActivationsApiTests.scala:328)
```

It failed on the `activations.length should be(response.length)`. 
The initial wait on view was ok; it confirmed at least one view was up to date. If couchdb is not clustered in [Travis](https://github.com/apache/incubator-openwhisk/blob/master/ansible/environments/local/hosts#L26), why does the query fail?

**Comment by rabbah** [comment]
answering my question: the `waitOnView` is checking the wrong index. The filtering by name using a different view. So need to adjust the wait.
