### ISSUE TITLE
failing test actionContainers.PythonActionContainerTests.python3action should be able to import additional packages as installed in the image

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk#3384]
```
org.scalatest.exceptions.TestFailedException: 502 was not equal to 200
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
	at actionContainers.PythonActionContainerTests$$anonfun$13$$anonfun$27.apply(PythonActionContainerTests.scala:422)
	at actionContainers.PythonActionContainerTests$$anonfun$13$$anonfun$27.apply(PythonActionContainerTests.scala:385)
	at actionContainers.ActionContainer$.withContainer(ActionContainer.scala:167)
	at actionContainers.PythonActionContainerTests.withActionContainer(PythonActionContainerTests.scala:39)
	at actionContainers.PythonActionContainerTests$$anonfun$13.apply$mcV$sp(PythonActionContainerTests.scala:385)
	at actionContainers.PythonActionContainerTests$$anonfun$13.apply(PythonActionContainerTests.scala:384)
	at actionContainers.PythonActionContainerTests$$anonfun$13.apply(PythonActionContainerTests.scala:384)
	```

**Comment by rabbah** [comment]
```
  File "pythonrunner.py", line 88, in run
    exec('fun = %s(param)' % self.mainFn, self.global_context)
  File "<string>", line 1, in <module>
  File "__main__.py", line 16, in main
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.6/site-packages/httplib2/__init__.py", line 995, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
```
