### ISSUE TITLE
Error thrown from MetricEmitter

### ISSUE THREAD

**Issue by dubeejw** [apache/incubator-openwhisk#3438]
We have observed an `ArrayIndexOutOfBoundsException` being thrown from `MetricEmitter`.

Line throwing the error:
https://github.com/apache/incubator-openwhisk/blob/6f1a445f22f827bd91f75b01bc82988054febbc8/common/scala/src/main/scala/whisk/common/Logging.scala#L237

Stack trace:
```
  | March 14th 2018, 12:45:05.553 | [2018-03-14T16:45:04.274Z] [WARN] Failed to store value -1 in HdrHistogram, please review your range configuration. | controller0

  | March 14th 2018, 12:45:05.560 | java.lang.ArrayIndexOutOfBoundsException: Histogram recorded value cannot be negative. | controller0

  | March 14th 2018, 12:45:05.561 | at org.HdrHistogram.AbstractHistogram.countsArrayIndex(AbstractHistogram.java:2181) | controller0

  | March 14th 2018, 12:45:05.562 | at org.HdrHistogram.AbstractHistogram.recordCountAtValue(AbstractHistogram.java:465) | controller0

  | March 14th 2018, 12:45:05.562 | at kamon.metric.instrument.HdrHistogram.tryRecord(Histogram.scala:160) | controller0

  | March 14th 2018, 12:45:05.562 | at org.HdrHistogram.AbstractHistogram.recordValueWithCount(AbstractHistogram.java:408) | controller0

  | March 14th 2018, 12:45:05.563 | at whisk.common.MetricEmitter$.emitHistogramMetric(Logging.scala:237) | controller0

  | March 14th 2018, 12:45:05.563 | at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:154) | controller0

  | March 14th 2018, 12:45:05.564 | at whisk.connector.kafka.KafkaConsumerConnector$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(KafkaConsumerConnector.scala:156) | controller0

  | March 14th 2018, 12:45:05.564 | at whisk.connector.kafka.KafkaConsumerConnector$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(KafkaConsumerConnector.scala:154) | controller0

  | March 14th 2018, 12:45:05.568 | at scala.Option.foreach(Option.scala:257) | controller0

  | March 14th 2018, 12:45:05.569 | at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:83) | controller0

  | March 14th 2018, 12:45:05.569 | at whisk.connector.kafka.KafkaConsumerConnector$$anonfun$2.apply$mcV$sp(KafkaConsumerConnector.scala:154) | controller0

  | March 14th 2018, 12:45:05.569 | at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:101) | controller0

  | March 14th 2018, 12:45:05.569 | at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) | controller0

  | March 14th 2018, 12:45:05.570 | at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43) | controller0

  | March 14th 2018, 12:45:05.570 | at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) | controller0

  | March 14th 2018, 12:45:05.570 | at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) | controller0

  | March 14th 2018, 12:45:05.570 | at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) | controller0

  | March 14th 2018, 12:45:05.571 | at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) | controller0

```

**Comment by dubeejw** [comment]
Closing as fixed.

**Comment by csantanapr** [comment]
@dubee what was the fix?

**Comment by markusthoemmes** [comment]
@csantanapr https://github.com/apache/incubator-openwhisk/commit/9c889222f9706f7a7b40e3ccbca78aa03f2d6d2c

**Comment by csantanapr** [comment]
Thanks for the link to the fix, was what I looking to see in this issue.

**Comment by csantanapr** [comment]
Yep I got the message of not longer already fixed on master. 
But closing the issue without a link to it didn’t look good.

**Comment by csantanapr** [comment]
Thanks for sharing the link to the fix @markusthoemmes 👍
