### ISSUE TITLE
KafkaConnectorTests heisenbug

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3523]
Following failure was seen on travis

```
Kafka connector should send and receive a kafka message even after session timeout 
org.scalatest.exceptions.TestFailedException: 1 was not equal to 3

at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
at services.KafkaConnectorTests$$anonfun$2.apply$mcV$sp(KafkaConnectorTests.scala:136)
at services.KafkaConnectorTests$$anonfun$2.apply(KafkaConnectorTests.scala:120)
at services.KafkaConnectorTests$$anonfun$2.apply(KafkaConnectorTests.scala:120)
```
Test output
```
Send message to topic.
Successfully sent message to topic: KafkaConnectorTestTopic-0@5
Receiving message from topic.
Received 1. Took 6 msec: List(Wed Apr 04 06:21:59 UTC 2018)
Send message to topic.
Successfully sent message to topic: KafkaConnectorTestTopic-0@6
Receiving message from topic.
Received 1. Took 5 msec: List(Wed Apr 04 06:21:59 UTC 2018)
Send message to topic.
Successfully sent message to topic: KafkaConnectorTestTopic-0@7
Receiving message from topic.
Received 2. Took 17 msec: List(Wed Apr 04 06:21:59 UTC 2018, Wed Apr 04 06:22:10 UTC 2018)
Send message to topic.
Successfully sent message to topic: KafkaConnectorTestTopic-0@8
Receiving message from topic.
Received 2. Took 13 msec: List(Wed Apr 04 06:21:59 UTC 2018, Wed Apr 04 06:22:10 UTC 2018)
Send message to topic.
Successfully sent message to topic: KafkaConnectorTestTopic-0@9
Receiving message from topic.
Received 1. Took 4 msec: List(Wed Apr 04 06:22:21 UTC 2018)
```
See in 
* https://scans.gradle.com/s/ith6wms6wtnua/tests/failed ([travis](https://travis-ci.org/apache/incubator-openwhisk/builds/361978262) (4-April-2018)
* https://scans.gradle.com/s/p4wqdppt34ilo/tests/failed

**Comment by chetanmeh** [comment]
https://scans.gradle.com/s/kjbvfxcbw3j7y/tests

Here failure was due to timeout

```
java.util.concurrent.TimeoutException: Futures timed out after [20 seconds]Close stacktrace
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
at scala.concurrent.Await$.result(package.scala:190)
at services.KafkaConnectorTests$$anonfun$sendAndReceiveMessage$1.apply(KafkaConnectorTests.scala:94)
```

**Comment by csantanapr** [comment]
Test is starting to failing again 
https://travis-ci.org/apache/incubator-openwhisk/jobs/379018740#L5021
```
services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after session timeout FAILED
    org.scalatest.exceptions.TestFailedException: 1 was not equal to 2
        at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
        at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
```

**Comment by chetanmeh** [comment]
Another failure seen at https://scans.gradle.com/s/6sfxa7kccvlji/tests/xaqugzlgs2zw6-6k6x5jmp5qe2c due to same reason as one above
