### ISSUE TITLE
ElasticSearchLogStoreTests heisenbug

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3577]
Following failure was seen on travis

```
org.scalatest.exceptions.TestFailedException: Expected exception akka.stream.StreamTcpException to be thrown, but akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1 was thrownClose stacktrace
at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:138)
at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:306)
at org.scalatest.words.ResultOfBeWordForAType.thrownBy(ResultOfBeWordForAType.scala:44)
at whisk.core.containerpool.logging.ElasticSearchLogStoreTests$$anonfun$6.apply(ElasticSearchLogStoreTests.scala:188)
at whisk.core.containerpool.logging.ElasticSearchLogStoreTests$$anonfun$6.apply(ElasticSearchLogStoreTests.scala:185)

```

Seen at 
* https://travis-ci.org/apache/incubator-openwhisk/jobs/370978540
* https://scans.gradle.com/s/aorstlxvccmmk/tests/failed

**Comment by markusthoemmes** [comment]
The same occured in splunk tests, will have a look!
