### ISSUE TITLE
RuncClientTests heisenbug

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3583]
Following failure was seen on travis due to timeout. Possibly the timeout needs to be increased

```
Caused by: 
java.util.concurrent.TimeoutException
: 
Futures timed out after [500 milliseconds]
Close stacktrace
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
at scala.concurrent.Await$.result(package.scala:190)
at whisk.core.containerpool.docker.test.RuncClientTests.await(RuncClientTests.scala:48)
```

See here
* https://scans.gradle.com/s/l7pbmmshz5ddk/tests/failed
* https://travis-ci.org/chetanmeh/incubator-openwhisk/builds/371225066

**Comment by markusthoemmes** [comment]
Yes, let's bump the timeout to 5 seconds, it's non-significant anyway. Want to do that?

**Comment by chetanmeh** [comment]
Was thinking to change such tests to use [ScalaFutures][1] with [IntegrationPatience][2] and avoid custom await logic. Thoughts?

[1]: http://doc.scalatest.org/3.0.0/index.html#org.scalatest.concurrent.ScalaFutures
[2]: http://doc.scalatest.org/3.0.0/index.html#org.scalatest.concurrent.IntegrationPatience

**Comment by chetanmeh** [comment]
> futureValue doesn't throw exceptions in a useful way (That's used for shouldBe thrownBy)

I tried and exception testing was fine

> is there much value of using futureValue over Await

I prefer the `ScalaFutures` as it expresses the intention clearly and keeps timeout handling consistent across usages with decent defaults (15 secs). Further it opens up the possibility of [scaling][1] the timeouts as per environment in a global way i.e. increasing the scaling factor for slow CI setups. Currently various test have there own specific  timeouts and which need to be tweaked as and when we see such failures. 

 Much of scalatest is anyway magical!

[1]: http://doc.scalatest.org/1.8/org/scalatest/concurrent/ScaledTimeSpans.html
