### ISSUE TITLE
InvokerSupervisionTests heisenbug

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3809]
Following failure was seen on travis

```
whisk.core.loadBalancer.test.InvokerSupervisionTests » InvokerPool should forward an ActivationMessage to the sendActivation-Method

Unsatisfied expectation: Expected: inAnyOrder { StubFunction2-3(whisk.system/utils/date?message={}, InstanceId(0,None)) any number of times (never called) StubFunction2-3(whisk.system/utils/date?message={}, InstanceId(0,None)) once (never called - UNSATISFIED) } Actual:

[2018-06-25T10:55:08.596Z] [INFO] [#tid_sid_invokerHealth] [InvokerPool] invoker status changed to 0 -> Healthy
[2018-06-25T10:55:08.611Z] [INFO] [#tid_sid_dispatcher] [MessageFeed] handler capacity = 4, pipeline fill at = 4, pipeline depth = 8
[2018-06-25T10:55:08.641Z] [ERROR] Can't log call to mock object, have expectations been verified already?
java.lang.RuntimeException: Can't log call to mock object, have expectations been verified already?
	at org.scalamock.function.FakeFunction.handle(FakeFunction.scala:46)
	at org.scalamock.function.FakeFunction2.apply(FakeFunction.scala:68)
	at whisk.core.loadBalancer.InvokerPool$$anonfun$receive$1.applyOrElse(InvokerSupervision.scala:116)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at whisk.core.loadBalancer.InvokerPool.aroundReceive(InvokerSupervision.scala:73)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2018-06-25T10:55:08.653Z] [INFO] [#tid_sid_dispatcher] [MessageFeed] handler capacity = 4, pipeline fill at = 4, pipeline depth = 8

```

https://scans.gradle.com/s/l23drmohxtvam/tests/xaqugzlgs2zw6-pe5egvx7auofs

**Comment by chetanmeh** [comment]
Seen again https://scans.gradle.com/s/36l5wo4kvbrv4/tests/xaqugzlgs2zw6-pe5egvx7auofs

**Comment by chetanmeh** [comment]
Seen again https://scans.gradle.com/s/fcm7gfyzbtc4c/tests/xaqugzlgs2zw6-pe5egvx7auofs
