### ISSUE TITLE
PG build failing for PR 3579 

### ISSUE THREAD

**Issue by Himavanth** [apache/incubator-openwhisk#4012]
@vvraskin is already helping me with the PG build for 
https://github.com/apache/incubator-openwhisk/pull/3579

Creating this issue just so i can track it.

## Environment details:

* IBM PG 

## Steps to reproduce the issue:

1.   Start a PG for https://github.com/apache/incubator-openwhisk/pull/3579

## Provide the expected results and outputs:

```
PG should not fail
```

## Provide the actual results and outputs:

```
PG fails with 
Error: Password file not found: /root/jmxremote.password
sun.management.AgentConfigurationError
at sun.management.jmxremote.ConnectorBootstrap.checkPasswordFile(ConnectorBootstrap.java:563)
at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:426)
at sun.management.Agent.startAgent(Agent.java:262)
at sun.management.Agent.startAgent(Agent.java:452)
mv: can't stat '/root/jmxremote.access': Permission denied
mv: can't stat '/root/jmxremote.password': Permission denied
chmod: /root/jmxremote.*: Permission denied
```

**Comment by Himavanth** [comment]
Has been worked upon and merged
