### ISSUE TITLE
Ping test should be more leninet in expected message

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#4013]
`Whisk actions should not be able to use 'ping' in an action` test currently checks for specific error message and thus fails for our setup where message is different. Ours `ping: permission denied (are you root?)` vs expected `ping: icmp open socket: Operation not permitted`

Test failure message

```
org.scalatest.exceptions.TestFailedException: Some({"stdout":"PING google.com (172.217.5.238): 56 data bytes\n","stderr":"ping: permission denied (are you root?)\n"}) was not equal to Some({"stderr":"ping: icmp open socket: Operation not permitted\n","stdout":""})
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at system.basic.WskActionTests$$anonfun$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$34.apply(WskActionTests.scala:269)
	at system.basic.WskActionTests$$anonfun$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$34.apply(WskActionTests.scala:268)
	at common.WskTestHelpers$$anonfun$withActivation$1.apply$mcV$sp(WskTestHelpers.scala:272)
```

Activation response

```json
{
  "duration": 276,
  "name": "ping",
  "subject": "guest",
  "activationId": "6fc4f220c3c842c484f220c3c852c4b0",
  "publish": false,
  "annotations": [
    {
      "key": "path",
      "value": "guest/ping"
    },
    {
      "key": "waitTime",
      "value": -15999
    },
    {
      "key": "kind",
      "value": "nodejs:6"
    },
    {
      "key": "limits",
      "value": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
      }
    },
    {
      "key": "initTime",
      "value": 236
    }
  ],
  "version": "0.0.1",
  "response": {
    "result": {
      "stdout": "PING google.com (172.217.5.238): 56 data bytes\n",
      "stderr": "ping: permission denied (are you root?)\n"
    },
    "success": true,
    "status": "success"
  },
  "end": 1536587099497,
  "logs": [
    "2018-09-10T13:44:59.463416166Z stdout: Pinging to google.com",
    "2018-09-10T13:44:59.495845721Z stdout: stdout PING google.com (172.217.5.238): 56 data bytes",
    "2018-09-10T13:44:59.495859034Z stdout: ",
    "2018-09-10T13:44:59.495862754Z stdout: stderr ping: permission denied (are you root?)",
    "2018-09-10T13:44:59.495866021Z stdout: "
  ],
  "start": 1536587099221,
  "namespace": "guest"
}
```

**Comment by chetanmeh** [comment]
Should we just check presence of "ping"  in `stderr`?

**Comment by markusthoemmes** [comment]
@chetanmeh is the successful case consistent? If so, we could negate a successful test, like 

```scala
logs should not include("bytes from")
```

**Comment by chetanmeh** [comment]
@markusthoemmes makes sense to negate a successful test. Changing the `ping.js` 

```diff
@@ -28,3 +28,5 @@
 
     return promise;
 }
+
+main({payload:"www.google.com"})
```

And then executing it `node ping.js` shows following

```
$ node ping.js
Pinging to www.google.com
stdout PING www.google.com (172.217.166.100): 56 data bytes
64 bytes from 172.217.166.100: icmp_seq=0 ttl=53 time=74.176 ms
64 bytes from 172.217.166.100: icmp_seq=1 ttl=53 time=106.975 ms

--- www.google.com ping statistics ---
3 packets transmitted, 2 packets received, 33.3% packet loss
round-trip min/avg/max/stddev = 74.176/90.576/106.975/16.399 ms

stderr 
```

Would create a PR for that change

**Comment by markusthoemmes** [comment]
Good one! Should we also add `should include("0 packets received")` and `should include("100% packet loss")`?
