### ISSUE TITLE
Intermittent failure in WskRuleTests with multiple controllers

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#4024]
While running the basic system test against an existing deployment having 2 controllers we are seeing intermittent failure in `Whisk rules should connect two triggers to two different actions, invoking them both eventually`. 

```
Starting test Whisk rules should connect two triggers to two different actions, invoking them both eventually at 2018-09-14 10:41:39.039
check failed for activation 1b82a5b96be14c8a82a5b96be12c8a82: {"name":"t1to1b-1536921699040","subject":"guest","activationId":"1b82a5b96be14c8a82a5b96be12c8a82","publish":false,"annotations":[],"version":"0.0.1","response":{"result":{"payload":"got four words, period"},"success":true,"status":"success"},"logs":["{\"statusCode\":0,\"success\":true,\"activationId\":\"cab3196ee64140d5b3196ee64130d540\",\"rule\":\"guest/r2to2c\",\"action\":\"guest/a1to1a-1536921699040\"}"],"start":1536921701364,"namespace":"guest"}
Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: List(RuleActivationResult(0,true,cab3196ee64140d5b3196ee64130d540,guest/a1to1a-1536921699040)) had size 1 instead of expected size 2
ERROR: deleting asset failed for r2to2d: org.scalatest.exceptions.TestFailedException: 404 was not equal to 200
```

And test failure trace is

```
org.scalatest.exceptions.TestFailedException: List(RuleActivationResult(0,true,cab3196ee64140d5b3196ee64130d540,guest/a1to1a-1536921699040)) had size 1 instead of expected size 2
    at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
    at org.scalatest.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2707)
    at system.basic.WskRuleTests$$anonfun$9$$anonfun$apply$mcV$sp$9$$anonfun$apply$34$$anonfun$apply$35.apply(WskRuleTests.scala:353)
    at system.basic.WskRuleTests$$anonfun$9$$anonfun$apply$mcV$sp$9$$anonfun$apply$34$$anonfun$apply$35.apply(WskRuleTests.scala:351)
    at common.WskTestHelpers$$anonfun$withActivation$1.apply$mcV$sp(WskTestHelpers.scala:272)
    at common.WskTestHelpers$class.withRethrowingPrint(WskTestHelpers.scala:304)
    at system.basic.WskRuleTests.withRethrowingPrint(WskRuleTests.scala:34)
    at common.WskTestHelpers$class.withActivation(WskTestHelpers.scala:271)
    at system.basic.WskRuleTests.withActivation(WskRuleTests.scala:34)
    at common.WskTestHelpers$class.withActivation(WskTestHelpers.scala:253)
    at system.basic.WskRuleTests.withActivation(WskRuleTests.scala:34)
    at system.basic.WskRuleTests$$anonfun$9$$anonfun$apply$mcV$sp$9$$anonfun$apply$34.apply(WskRuleTests.scala:351)
    at system.basic.WskRuleTests$$anonfun$9$$anonfun$apply$mcV$sp$9$$anonfun$apply$34.apply(WskRuleTests.scala:349)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at system.basic.WskRuleTests$$anonfun$9$$anonfun$apply$mcV$sp$9.apply(WskRuleTests.scala:349)
    at system.basic.WskRuleTests$$anonfun$9$$anonfun$apply$mcV$sp$9.apply(WskRuleTests.scala:329)
    at common.WskTestHelpers$class.withAssetCleaner(WskTestHelpers.scala:198)
```

Relates to #4003

**Comment by chetanmeh** [comment]
What is happening here is that test creates 2 triggers and 2 actions first. Then it creates 4 rules r2to2a, r2to2b etc such that each trigger gets linked to 2 action. Then test asserts that upon trigger activation there are 2 linked activations for 2 actions. However in some cases it finds only 1 activation.

Upon checking logs following sequence happens for trigger `t1to1b-1536921699040`

#### Create trigger

Trigger gets created on Controller at 10.66.20.28 

```
[2018-09-14T10:41:39.470Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] PUT /api/v1/namespaces/_/triggers/t1to1b-1536921699040 
[2018-09-14T10:41:39.470Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [BasicAuthenticationDirective] authenticate: 2ed4ad48-9212-4ebc-a7fb-d7a9b61d4433
[2018-09-14T10:41:39.470Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [Identity] [GET] serving from cache: CacheKey(2ed4ad48-9212-4ebc-a7fb-d7a9b61d4433) [marker:database_cacheHit_count:0]
[2018-09-14T10:41:39.471Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [WhiskTrigger] [GET] serving from datastore: CacheKey(guest/t1to1b-1536921699040) [marker:database_cacheMiss_count:1]
[2018-09-14T10:41:39.471Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [CosmosDBArtifactStore] [GET] 'whisks' finding document: 'id: guest/t1to1b-1536921699040' [marker:database_getDocument_start:1]
[2018-09-14T10:41:39.478Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [CosmosDBArtifactStore]  [marker:database_getDocument_finish:8:7]
[2018-09-14T10:41:39.478Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [WhiskTrigger] invalidating CacheKey(guest/t1to1b-1536921699040)
[2018-09-14T10:41:39.478Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [WhiskTrigger] write initiated on new cache entry
[2018-09-14T10:41:39.478Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [CosmosDBArtifactStore] [PUT] 'whisks' saving document: 'id: guest|t1to1b-1536921699040, rev: null' [marker:database_saveDocument_start:8]
[2018-09-14T10:41:39.489Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [CosmosDBArtifactStore]  [marker:database_saveDocument_finish:19:11]
[2018-09-14T10:41:39.489Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [WhiskTrigger] write all done, caching CacheKey(guest/t1to1b-1536921699040) Cached
[2018-09-14T10:41:39.490Z] [INFO] [#tid_cbyZDmV5qhHEld2shjmruoW3SAEcR54Q] [BasicHttpService] [marker:http_put.200_count:19:19]
```

#### Rule r2to2c updates the trigger

r2to2c rule creation lead to trigger getting updated on Controller at ip 10.66.20.84 

```
[2018-09-14T10:41:40.809Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] PUT /api/v1/namespaces/_/rules/r2to2c 
[2018-09-14T10:41:40.810Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [BasicAuthenticationDirective] authenticate: 2ed4ad48-9212-4ebc-a7fb-d7a9b61d4433
[2018-09-14T10:41:40.810Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [Identity] [GET] serving from cache: CacheKey(2ed4ad48-9212-4ebc-a7fb-d7a9b61d4433) [marker:database_cacheHit_count:1]
[2018-09-14T10:41:40.810Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore] [GET] 'whisks' finding document: 'id: guest/r2to2c' [marker:database_getDocument_start:1]
[2018-09-14T10:41:40.817Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore]  [marker:database_getDocument_finish:8:6]
[2018-09-14T10:41:40.817Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [WhiskTrigger] [GET] serving from datastore: CacheKey(guest/t1to1b-1536921699040) [marker:database_cacheMiss_count:8]
[2018-09-14T10:41:40.817Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore] [GET] 'whisks' finding document: 'id: guest/t1to1b-1536921699040' [marker:database_getDocument_start:8]
[2018-09-14T10:41:40.821Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore]  [marker:database_getDocument_finish:12:4]
[2018-09-14T10:41:40.821Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [WhiskActionMetaData] [GET] serving from cache: CacheKey(guest/a1to1a-1536921699040) [marker:database_cacheHit_count:12]
[2018-09-14T10:41:40.821Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [WhiskTrigger] write initiated on existing cache entry, invalidating CacheKey(guest/t1to1b-1536921699040), tid usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj, state WriteInProgress
[2018-09-14T10:41:40.821Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore] [PUT] 'whisks' saving document: 'id: guest|t1to1b-1536921699040, rev: "01002266-0000-0000-0000-5b9b90630000"' [marker:database_saveDocument_start:12]
[2018-09-14T10:41:40.833Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore]  [marker:database_saveDocument_finish:24:12]
[2018-09-14T10:41:40.833Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [WhiskTrigger] write all done, caching CacheKey(guest/t1to1b-1536921699040) Cached
[2018-09-14T10:41:40.833Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore] [PUT] 'whisks' saving document: 'id: guest|r2to2c, rev: null' [marker:database_saveDocument_start:24]
[2018-09-14T10:41:40.843Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [CosmosDBArtifactStore]  [marker:database_saveDocument_finish:34:10]
[2018-09-14T10:41:40.843Z] [INFO] [#tid_usZszyKeMJcEETfTuWOtKY8ItmvPo1Kj] [BasicHttpService] [marker:http_put.200_count:34:34]

```

#### r2to2d fails to update the trigger due to conflict

When rule r2to2d tries to update the same trigger on Controller at ip 10.66.20.28  then it ends in a conflict

```
[2018-09-14T10:41:41.111Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] PUT /api/v1/namespaces/_/rules/r2to2d 
[2018-09-14T10:41:41.111Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [BasicAuthenticationDirective] authenticate: 2ed4ad48-9212-4ebc-a7fb-d7a9b61d4433
[2018-09-14T10:41:41.111Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [Identity] [GET] serving from cache: CacheKey(2ed4ad48-9212-4ebc-a7fb-d7a9b61d4433) [marker:database_cacheHit_count:0]
[2018-09-14T10:41:41.112Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [CosmosDBArtifactStore] [GET] 'whisks' finding document: 'id: guest/r2to2d' [marker:database_getDocument_start:1]
[2018-09-14T10:41:41.119Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [CosmosDBArtifactStore]  [marker:database_getDocument_finish:7:6]
[2018-09-14T10:41:41.119Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [WhiskTrigger] [GET] serving from cache: CacheKey(guest/t1to1b-1536921699040) [marker:database_cacheHit_count:8]
[2018-09-14T10:41:41.119Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [WhiskActionMetaData] [GET] serving from cache: CacheKey(guest/a1to1b-1536921699040) [marker:database_cacheHit_count:8]
[2018-09-14T10:41:41.119Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [WhiskTrigger] write initiated on existing cache entry, invalidating CacheKey(guest/t1to1b-1536921699040), tid PCZdOzzF76jZmykwB58XlwRdmgcsmeZa, state WriteInProgress
[2018-09-14T10:41:41.119Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [CosmosDBArtifactStore] [PUT] 'whisks' saving document: 'id: guest|t1to1b-1536921699040, rev: "01002266-0000-0000-0000-5b9b90630000"' [marker:database_saveDocument_start:8]
[2018-09-14T10:41:41.128Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [CosmosDBArtifactStore]  [marker:database_saveDocument_finish:17:9]
[2018-09-14T10:41:41.128Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [WhiskTrigger] invalidating CacheKey(guest/t1to1b-1536921699040)
[2018-09-14T10:41:41.129Z] [INFO] [#tid_PCZdOzzF76jZmykwB58XlwRdmgcsmeZa] [BasicHttpService] [marker:http_put.409_count:18:18]

```

**Comment by chetanmeh** [comment]
In summary following sequence of events happened

1. Trigger gets created on C1. It also gets cached here with rev r1
2. r2to2c updates the trigger on C2. As its not in cache it is read at rev r1 and updated to rev r2 (not seen in logs)
3. Then r2to2d tries to update the trigger on C1. Here it finds the entry in cache and hence tries to update using rev r1 and end up in conflict
4. So due to conflict the trigger gets linked to only one action. Here the test case should have failed for conflict but it moved on ...
5. When this trigger gets evaluated then as only one action is configured it leads to test failure.

As our regular test on travis only run with 1 Controller and 1 Invoker this failure is not seen.

### Testcase not failing on conflict

It probably happens because `WskRestOperations` uses the `SwaggerValidator` to validate expected response for each HTTP call made. This validation checks against expected response code from swagger defn which in this case do list 409 as expected response. And hence test flow misses to detect that it should have failed at that point.

Probably here test should check if all prior operation result in 202 or 200

### Why intermittent failure

May be in success case the cache entry gets invalidated before second trigger update happens or request land on same node

Is above understanding correct?

**Comment by rabbah** [comment]
@mdeuser @jasonpet this vaguely reminds me of heisenbugs from the past --- does it sound familiar?

**Comment by rabbah** [comment]
@chetanmeh your explanation and understanding makes sense to me.

**Comment by mdeuser** [comment]
i also agree that the cross-controller cache latency is the core of this issue.
