### ISSUE TITLE
WskConductorTests Heisenbug

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#4152]
See failure at https://scans.gradle.com/s/vuyyrjush3mhi/tests/xaqugzlgs2zxa-snmxss4idqdgw `Whisk conductor actions should invoke nested conductor actions`

```
org.scalatest.exceptions.TestFailedException: "[action developer error]" was not equal to "[success]"Open stacktrace
check failed for activation ce77a9057caa4261b7a9057caa326137: {"activationId":"ce77a9057caa4261b7a9057caa326137","annotations":[{"key":"topmost","value":true},{"key":"path","value":"guest/conductor"},{"key":"conductor","value":true},{"key":"kind","value":"sequence"},{"key":"limits","value":{"concurrency":1,"logs":10,"memory":256,"timeout":60000}}],"duration":6,"end":1543840917806,"logs":["942caf2627f14c3cacaf2627f18c3c00"],"name":"conductor","namespace":"guest","publish":false,"response":{"result":{"error":"The action did not produce a valid response and exited unexpectedly."},"status":"action developer error","success":false},"start":1543840905771,"subject":"guest","version":"0.0.1"}
Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: "[action developer error]" was not equal to "[success]"
org.scalatest.exceptions.TestFailedException: "[action developer error]" was not equal to "[success]"
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at system.basic.WskConductorTests.$anonfun$new$29(WskConductorTests.scala:269)
	at system.basic.WskConductorTests.$anonfun$new$29$adapted(WskConductorTests.scala:268)
	at common.WskTestHelpers.$anonfun$withActivation$2(WskTestHelpers.scala:272)
	at common.WskTestHelpers.withRethrowingPrint(WskTestHelpers.scala:304)
	at common.WskTestHelpers.withRethrowingPrint$(WskTestHelpers.scala:303)
	at system.basic.WskConductorTests.withRethrowingPrint(WskConductorTests.scala:33)
	at common.WskTestHelpers.withActivation(WskTestHelpers.scala:272)
	at common.WskTestHelpers.withActivation$(WskTestHelpers.scala:260)
	at system.basic.WskConductorTests.withActivation(WskConductorTests.scala:33)
	at common.WskTestHelpers.withActivation(WskTestHelpers.scala:253)
	at common.WskTestHelpers.withActivation$(WskTestHelpers.scala:241)
	at system.basic.WskConductorTests.withActivation(WskConductorTests.scala:33)
	at system.basic.WskConductorTests.$anonfun$new$22(WskConductorTests.scala:268)
	at system.basic.WskConductorTests.$anonfun$new$22$adapted(WskConductorTests.scala:189)
	at common.WskTestHelpers.withAssetCleaner(WskTestHelpers.scala:198)
	at common.WskTestHelpers.withAssetCleaner$(WskTestHelpers.scala:193)
	at system.basic.WskConductorTests.withAssetCleaner(WskConductorTests.scala:33)
	at system.basic.WskConductorTests.$anonfun$new$21(WskConductorTests.scala:189)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
```

**Comment by chetanmeh** [comment]
Another failure seen in https://scans.gradle.com/s/czbfhiubrtfme/tests/failed

* Whisk conductor actions should invoke nested conductor actions
* Wsk Sequence should execute a sequence in blocking fashion and finish execution even if longer than blocking response timeout

**Comment by dgrove-oss** [comment]
Speculation was that bumping nodejs to 6.15.1 was likely to resolve this (regression in 6.15.0 seemed like a possible cause).  Was this run before or after https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/102 was merged?

**Comment by chetanmeh** [comment]
Last failure was around 20 hrs ago and above merge is 17 hrs ago. So failure is seen before the merge. What was the regression?

**Comment by dgrove-oss** [comment]
There was a regression in NodeJS 6.15.0 that was fixed in a 6.15.1 release (https://nodejs.org/en/blog/release/v6.15.1/) when we picked up 6.15.0 to get the security updates we got hit with the bad version of nodejs, which led to hiesenbugs in JS actions.

**Comment by chetanmeh** [comment]
Looks related. Lets keep a watch and then we can close it if we do not observe it for next few days
