### ISSUE TITLE
NPE in ShardingContainerPoolBalancer.emitHistogramMetric on start

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#4285]
As discussed on Slack following exception is being seen on startup 

```
```[2019-02-13T12:22:14.970Z] [ERROR] null
java.lang.NullPointerException: null
        at org.apache.openwhisk.core.loadBalancer.ShardingContainerPoolBalancer.emitHistogramMetric(ShardingContainerPoolBalancer.scala:170)
        at org.apache.openwhisk.core.loadBalancer.CommonLoadBalancer.$anonfun$new$1(CommonLoadBalancer.scala:80)
        at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:102)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:101)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)```
```

This seems to happen because scheduled job to emit metrics is getting invoked very early before the `ShardingContainerPoolBalancer` object is completely initialized and hence finds  one of the fields to be null. Possible fix

1. Delay the job by some time to ensure object is initialized
2. Have an explicit method to trigger scheduler and have sub class call them after initialization is complete

**Comment by sven-lange-last** [comment]
@SugandhaAgrawal would you please take a look?
