### ISSUE TITLE
MesosContainerFactory throws exceptions in succeeding Travis Unit Tests

### ISSUE THREAD

**Issue by mhenke1** [apache/incubator-openwhisk#4521]
The latest green Travis builds contain stack traces caused by  OutOfMemory  exceptions
in the MesosContainerFactory.

The errors happen asynchronously at different times and do not seem to affect 
the build result

## Environment details:

* OW Travis build

## Steps to reproduce the issue:

1.   Run Travis Unit Test

## Provide the expected results and outputs:

```
No stacktraces in build output
```

## Provide the actual results and outputs:

```
.....
 Uncaught error from thread [MesosActorSystem-akka.actor.default-dispatcher-8]: Java heap space, shutting down ActorSystem[MesosActorSystem]
    java.lang.OutOfMemoryError: Java heap space
....
```

**Comment by chetanmeh** [comment]
Some stacktraces where error was seen

```
org.apache.openwhisk.core.containerpool.docker.test.ApacheBlockingContainerClientTests > ApacheBlockingContainerClient should retry till timeout on HttpHostConnectException STANDARD_ERROR
    Uncaught error from thread [MesosActorSystem-akka.actor.default-dispatcher-9]: Java heap space, shutting down ActorSystem[MesosActorSystem]
    java.lang.OutOfMemoryError: Java heap space
    	at java.util.Arrays.copyOf(Arrays.java:3236)
    	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    	at java.io.PrintStream.write(PrintStream.java:480)
    	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
    	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
    	at java.io.PrintStream.write(PrintStream.java:527)
    	at java.io.PrintStream.print(PrintStream.java:669)
    	at java.io.PrintStream.println(PrintStream.java:806)
    	at org.apache.openwhisk.common.PrintStreamLogging.emit(Logging.scala:127)
    	at org.apache.openwhisk.common.Logging.error(Logging.scala:75)
    	at org.apache.openwhisk.common.Logging.error$(Logging.scala:74)
    	at org.apache.openwhisk.common.PrintStreamLogging.error(Logging.scala:107)
    	at org.apache.openwhisk.core.mesos.MesosContainerFactory$$anonfun$org$apache$openwhisk$core$mesos$MesosContainerFactory$$subscribe$1.applyOrElse(MesosContainerFactory.scala:117)
    	at org.apache.openwhisk.core.mesos.MesosContainerFactory$$anonfun$org$apache$openwhisk$core$mesos$MesosContainerFactory$$subscribe$1.applyOrElse(MesosContainerFactory.scala:115)
    	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
    	at scala.concurrent.Future$$Lambda$2042/349368846.apply(Unknown Source)
    	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    	at scala.concurrent.impl.Promise$$Lambda$760/1259518132.apply(Unknown Source)
    	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
    	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$757/325318635.apply$mcV$sp(Unknown Source)
    	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
    	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
    	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    Uncaught error from thread [MesosActorSystem-akka.actor.default-dispatcher-4]: Java heap space, shutting down ActorSystem[MesosActorSystem]
    java.lang.OutOfMemoryError: Java heap space
    	at java.util.Arrays.copyOf(Arrays.java:3236)
    	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    	at java.io.PrintStream.write(PrintStream.java:480)
    	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
    	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
    	at java.io.PrintStream.write(PrintStream.java:527)
    	at java.io.PrintStream.print(PrintStream.java:669)
    	at java.io.PrintStream.println(PrintStream.java:806)
    	at org.apache.openwhisk.common.PrintStreamLogging.emit(Logging.scala:127)
    	at org.apache.openwhisk.common.Logging.error(Logging.scala:75)
    	at org.apache.openwhisk.common.Logging.error$(Logging.scala:74)
    	at org.apache.openwhisk.common.PrintStreamLogging.error(Logging.scala:107)
    	at org.apache.openwhisk.core.mesos.MesosContainerFactory$$anonfun$org$apache$openwhisk$core$mesos$MesosContainerFactory$$subscribe$1.applyOrElse(MesosContainerFactory.scala:117)
    	at org.apache.openwhisk.core.mesos.MesosContainerFactory$$anonfun$org$apache$openwhisk$core$mesos$MesosContainerFactory$$subscribe$1.applyOrElse(MesosContainerFactory.scala:115)
    	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
    	at scala.concurrent.Future$$Lambda$2042/349368846.apply(Unknown Source)
    	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    	at scala.concurrent.impl.Promise$$Lambda$760/1259518132.apply(Unknown Source)
    	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
    	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$757/325318635.apply$mcV$sp(Unknown Source)
    	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
    	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
    	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)```

**Comment by chetanmeh** [comment]
`MesosContainerFactoryTest` does shutdown the actorSystem in `afterAll`. So not sure how the scheduled job continues to run even after tests are done. Even if the shutdown call failed it should have logged something like "Failed to stop" on console which I do not see in travis logs

See https://travis-ci.org/apache/incubator-openwhisk/jobs/550162367 for details

**Comment by chetanmeh** [comment]
Strangely even after clean shutdown of actorSystem I still see the dispatcher threads active which explains why the logging is eating up all memory

<img width="667" alt="image" src="https://user-images.githubusercontent.com/664531/60176078-edfbce00-9832-11e9-8370-93586c5b1eeb.png">

**Comment by chetanmeh** [comment]
Opened #4541 to fix this. Though I am still not clear on why even after closing the actor system the subscribe task continued to execute.
